Various fixes, need to backup for new laptop

diff --git a/bin/cicd b/bin/cicd
--- a/bin/cicd
+++ b/bin/cicd
@@ -1,35 +1,35 @@
 #!/bin/bash
 if [ -z "$1" ]; then
     branch=`get_current_project_repo_branch`
-else
-    branch="$1"
-fi
-
-prefix=`echo $branch | cut -d'-' -f1`
-
-# Convert branch prefix to cicd name.
-if [ $prefix == "PRIM" ]; then
-    project_name="Prime"
-elif [ $prefix == "SWCON2" ]; then
-    project_name="swcv2"
-elif [ $prefix == "TFNSW" ]; then
-    project_name="RMS"
-elif [ $prefix == "MET" ]; then
-    project_name="Metro"
-elif [ $prefix == "BAI" ]; then
-    project_name="bai"
-elif [ $prefix == "CTS" ]; then
-    project_name="CTS"
-elif [ $prefix == "LIN" ]; then
-    project_name="linbeck"
-elif [ $prefix == "SWDEL2" ]; then
-    project_name="swdv2"
-else
-    echo "Error: Branch prefix unknown."
-    exit 1
 fi
 
 cicd=`config cicd_url`
-url="$cicd/job/$project_name/job/$branch/"
-source "$HOME/setup/of"
-of firefox "$url" &
+for b in "$@"; do
+
+    prefix=`echo $b | cut -d'-' -f1`
+
+    # Convert branch prefix to cicd name.
+    if [ $prefix == "PRIM" ]; then
+        project_name="Prime"
+    elif [ $prefix == "SWCON2" ]; then
+        project_name="swcv2"
+    elif [ $prefix == "TFNSW" ]; then
+        project_name="RMS"
+    elif [ $prefix == "BAI" ]; then
+        project_name="bai"
+    elif [ $prefix == "CTS" ]; then
+        project_name="CTS"
+    elif [ $prefix == "LIN" ]; then
+        project_name="linbeck"
+    elif [ $prefix == "SWDEL2" ]; then
+        project_name="swdv2"
+    else
+        echo "Error: Branch prefix unknown."
+        exit 1
+    fi
+
+    url="$cicd/job/$project_name/job/$b/"
+    source "$HOME/setup/of"
+    of firefox "$url" &
+
+done
diff --git a/bin/qaf b/bin/qaf
--- a/bin/qaf
+++ b/bin/qaf
@@ -1,14 +1,16 @@
 #!/bin/bash
 
 if [ -z "$1" ]; then
-    echo "Usage: $0 <branch>"
+    echo "Usage: $0 <branches>"
     exit 1
 fi
 
-project_name=`task_code_to_project_name $1` || { echo "Error: invalid branch name" ; exit 1; }
+for branch in "$@"; do
+    project_name=`task_code_to_project_name $branch` || { echo "Error: invalid branch name: $branch" ; exit 1; }
 
-if [[ "$project_name" == "swdeliveryv2" ]]; then
-    project_name="swdelivery"
-fi
-source "$HOME/setup/of"
-of firefox "https://$1.$project_name.qa.finao.com.au"
+    if [[ "$project_name" == "swdeliveryv2" ]]; then
+        project_name="swdelivery"
+    fi
+    source "$HOME/setup/of"
+    of firefox "https://$branch.$project_name.qa.finao.com.au"
+done
