nt: now a bash function, remembers task code and initialises new terminals in correct directory v*: remove some duplicated scripting, now works independent of cwd bl: blacklight (keyboard) caffeine: keep computer awake dark: better code gc: don't add commits to certain branches gchb: helper (can delete) gcp: now cherry-pick gd, gda: includes even unstaged changes gmm: now pulls on master gp: now creates PRs even if changes are limited to composer.(json|lock) gr: git restore hs: new screen layout l: tail logs master: switch to master all repos mf: make form mr: make route rd: route diff rdp: route diff paths r:l: include middleware s: exclude libs dir and a few other file types sf: seed features sv: search in vim too swd_rollout: helper uc: better branch aliasing for new packages i3config: add v: remember file position

diff --git a/bin/gc b/bin/gc
--- a/bin/gc
+++ b/bin/gc
@@ -1,6 +1,12 @@
 #!/bin/bash
 branch=`git branch --show-current`
 
+# Don't add commits directly to inductiondoc/bidfood, links/dlp, links/swd
+if [ "$branch" = "bidfood" ] || [ "$branch" = "dlp" ] || [ "$branch" = "swd" ]; then
+    echo "Error: cannot commit to bidfood/dlp/swd package branches."
+    exit 1
+fi
+
 # If currently on the master branch, swap to a branch name from
 # whichever project repo is not on master.
 if [ "$branch" = "master"  ]; then
