Make gc, gca, gcp, gcap support vim editor for large commit messages gc, gca, gcp, gcap: don't commit on master branch. If the current branch is master, switch to a new branch with the same name as whichever project repo is not on master. gp: fix line 14: /home/setup/log/pull_requests: No such file or directory gp: if it is a project repo and the changes are only composer.json/composer.lock, don't open PR page. screen: don't use -: in file name r:l: output stderr of artisan command nt: fix bug where swconnect is not being reset to master. gp: only open firefox if a url was found vim: if it is a directory, don't edit it, cd into it. v: shorter vim s: More efficient by performing one grep and not traversing certain subdirectories. vim: better indentation on blade templates qa: kubectl get pods -A | grep -i <branch> - kubectl -n <namespace> exec -it <name> -c php -- bash

diff --git a/bin/gc b/bin/gc
--- a/bin/gc
+++ b/bin/gc
@@ -1,3 +1,28 @@
 #!/bin/bash
 branch=`git branch --show-current`
-git commit -m "$branch $@"
+
+# If currently on the master branch, swap to a branch name from
+# whichever project repo is not on master.
+if [ "$branch" = "master" ]; then
+
+    # Identify which branch is not master.
+    branch=""
+    for project in bai bidfood cts dlp linbeck prime rms swconnect swdeliveryv2 watertight; do
+        project_branch=`cd $HOME/git/$project && git branch --show-current`
+        if [ "$project_branch" != "master" ]; then
+            branch="$project_branch"
+        fi
+    done
+
+    if [ -z "$branch" ]; then
+        echo "Error: cannot commit to master."
+        exit 1
+    fi
+    gsw "$branch"
+fi
+
+if [ -z "$1" ]; then
+    git commit
+else
+    git commit -m "$branch $@"
+fi
