SWDEL2-8283  Some changes...

diff --git a/bin/j b/bin/j
--- a/bin/j
+++ b/bin/j
@@ -1,11 +1,12 @@
 #!/bin/bash
 
-# Check argument exists
 if [ -z "$1" ]; then
-    echo "Usage: $0 <branch>"
-    exit 1
+    branch=`get_current_project_repo_branch`
+else
+    branch="$1"
 fi
 
-project_name=`task_code_to_project_name $1` || { echo "Error: invalid branch name" ; exit 1; }
+project_name=`task_code_to_project_name $branch` || { echo "Error: invalid branch name" ; exit 1; }
 
-firefox "https://finao-aus.atlassian.net/browse/$1"
+source "$HOME/.bashrc"
+of firefox "https://finao-aus.atlassian.net/browse/$branch"
