.gitignore: no need to commit changes to logfiles cb: fix a typo branch name dlp/swd gcap: git add --all always, show git status afterwards gsw: fix $? bug in bash if statement condition nt: exit if argument is not provided, validate new branch name (i.e. PRIM-1234 not PRIN-1234), run b:u at the end of nt, remove set -x. gp: compare with origin master qa: ensure connecting to deploy instances, remove set -x s: include results from libs dir, exclude from storage and build dirs grep_exclusions: exclude bootstrap.css qadb: to lower the branch name i3r: loads i3 window layout that I like ao: Change audio output to speakers/headphones.

diff --git a/bin/nt b/bin/nt
--- a/bin/nt
+++ b/bin/nt
@@ -1,7 +1,18 @@
 #!/bin/bash
+set -x
 
+# Check argument exists
 if [ -z "$1" ]; then
     echo "Usage: $0 <branch>"
+    exit 1
+fi
+
+# Check validity of the branch name
+echo $1 | grep -e "BAI-" -e "BID-" -e "CTS-" -e "DLP-" -e "LIN-" -e "PRIM-" -e "TFNSW-" -e "SWCON2-" -e "SWDEL2-" -e "WAT-"
+valid=$?
+if [ $valid -eq 1 ]; then
+    echo "Error: invalid branch name"
+    exit 1
 fi
 
 dir=`pwd`
@@ -12,3 +23,4 @@ done
 
 cd $dir && git stash > /dev/null && gsw "$1"
 cb
+b:u
