v: properly follow symlinks when changing directory cup: run in background in /tmp files to allow coding to continue as cup processes r:l: filter routes THEN do columns nt: git pull on master branch if new or existing task ap, uc, cb: don't read from vendor/finao. Read from composer.json instead ntcup: run nt followed by cup for one or more tasks a few extra helper commands

diff --git a/bin/nt b/bin/nt
--- a/bin/nt
+++ b/bin/nt
@@ -1,25 +1,23 @@
 #!/bin/bash
 
+set -x
+
 # Check argument exists
 if [ -z "$1" ]; then
     echo "Usage: $0 <branch>"
     exit 1
 fi
 
-# Check validity of the branch name
-echo $1 | grep -e "BAI-" -e "BID-" -e "CTS-" -e "DLP-" -e "LIN-" -e "PRIM-" -e "TFNSW-" -e "SWCON2-" -e "SWDEL2-" -e "WAT-" > /dev/null
-valid=$?
-if [ $valid -eq 1 ]; then
-    echo "Error: invalid branch name"
-    exit 1
-fi
-
-dir=`pwd`
+# Convert branch name to repo path
+project_name=`task_code_to_project_name $1` || { echo "Error: invalid branch name" ; exit 1; }
+project_repo="$HOME/git/$project_name"
 
 for project in bai bidfood cts dlp linbeck prime rms swconnect swdeliveryv2 watertight; do
-    cd $HOME/git/$project && git stash > /dev/null && gsw master > /dev/null
+    cd $HOME/git/$project && git stash > /dev/null && gsw master > /dev/null && git pull origin master & > /dev/null
 done
 
-cd $dir && git stash > /dev/null && gsw "$1"
+wait
+
+cd $project_repo && git stash > /dev/null && gsw "$1" && git pull origin "$1" 2> /dev/null
 cb
 b:u &> /dev/null &
