cup: get branch alias via package composer.json instead of greatest number on repos site, as "as ..." only if alias is required. r:l is no longer broken due to laravel 9 update truncating output based on terminal size id: new command to run tinker script to init db - set all passwords - clear all images qa: add error message for "No such running pod <task>" gsa: show colour even when called in a script cb: call gsa (new unified command) add main.css.map to grep exclusions

diff --git a/bin/qa b/bin/qa
--- a/bin/qa
+++ b/bin/qa
@@ -20,7 +20,10 @@ if [ $ret -eq 1 ]; then
 fi
 
 pod=`echo "$pods" | grep "Running" | grep "$lower_branch-deploy" | tr -s ' '`
-echo $pod
+if [ -z "$pod" ]; then
+    echo "Error: no such running pod $lower_branch"
+    exit 1
+fi
 namespace=$(echo "$pod" | cut -d' ' -f1)
 name=$(echo "$pod" | cut -d' ' -f2)
 
