cb: Make work on more branch names. gc: Add repo name to commit messages. get_project_from_current_directory: adjust to work in cup command tmp file structure gp: Specify origin <branch> in git push command. open_cicd: Rename to cicd gsw/c: Ability to switch off existing branch nt: Move into bash function so working directory can change. os: Adjust for new office monitor. q:w: increase memory allocation task_code_to_project_name: improve error message init_database.php: Update terry@finao.com.au to admin@finao.com.au so monkeyscripts can still autologin. New commands: c:c: Clear the cache d: gcap and cup. esrm: Remove elasticsearch index by prefix of index name firefox: Ensure correct version is used. fm: Open all manage tables of local site gda: Git diff of all repos gpu: Git push j: Open jira task kaf: kubectl apply kgc: kubectl get configmap kc: Use above two commands to change config of a qa. m: php artisan migrate m:r: php artisan migrate:rollback q:c: queue clear qaf: Open QA in firefox rmc: gcap "Resolve merge conflicts" rnt: Rollout new task rollout: Attempt to automate the rollout process s:i: php artisan search:index --force-update sand: Files which match two greps sd: php artisan db:seed --class=DropdownsSeeder sn: seed notifications sor: Files with match either or two greps vall: Edit files in each project repo vgs: Edit the global search indexed models.

diff --git a/bin/task_code_to_project_name b/bin/task_code_to_project_name
--- a/bin/task_code_to_project_name
+++ b/bin/task_code_to_project_name
@@ -26,6 +26,6 @@ elif [[ "$1" == "SWDEL2-"* ]]; then
 elif [[ "$1" == "WAT-"* ]]; then
     echo "watertight"
 else
-    echo "Error: invalid task code" >&2
+    echo "Error: invalid task code: $1" >&2
     exit 1
 fi
